version: 2
updates:
  # Control sobre las dependencias de Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  
  # Control sobre las dependencias de Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"

  # Control sobre las dependencias de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"